### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by JacquesMarais** [moklick/frontend-stuff#2741]
Please add some event libraries like Keyder.js

**Comment by moklick** [comment]
good idea

**Comment by JacquesMarais** [comment]
Cool

**Comment by JacquesMarais** [comment]
There are also many more other event libraries out there but I suggest Keyder.js.

**Comment by JacquesMarais** [comment]
Oh please could you remove issue #2739 it's offensive.

**Comment by Inflatables12** [comment]
great

**Comment by moklick** [comment]
@JacquesMarais Do you have some good ones you used in production?

**Comment by JacquesMarais** [comment]
[Bean](https://github.com/fat/bean), [EventEmitter](https://github.com/Wolfy87/EventEmitter), [Events.js](https://github.com/kbjr/Events.js), [KeyderJS](https://github.com/GethisOrg/KeyderJS) and [Minivents](https://github.com/allouis/minivents).

**Comment by moklick** [comment]
cool stuff, thanks! I will add them later.

**Comment by JacquesMarais** [comment]
Great, thanks.

**Comment by moklick** [comment]
When working with events in JS it's always a challenge to support all browsers. From your list only "bean" points out which browsers are supported. I would not add one of the others to the list.

**Comment by JacquesMarais** [comment]
KeyderJS does have browser compatibility listed.
