### ISSUE TITLE
Add mini.css

### ISSUE THREAD

**Issue by Chalarangelo** [moklick/frontend-stuff#2830]
Hi, I am the developer of **mini.css**, a minimal, responsive, style-agnostic CSS framework. 

You can check it out here: https://github.com/Chalarangelo/mini.css

I'd love to get more people involved and see more people use it so, if you think it's worthwhile, please add it to the list!

**Comment by moklick** [comment]
Hey @Chalarangelo,

thanks! Just do a PR.
