### ISSUE TITLE
Add Highcharts

### ISSUE THREAD

**Issue by stpoa** [moklick/frontend-stuff#2833]
Hi,

Where are highcharts? Most advanced JavaScript charting library on earth?

https://github.com/highcharts/highcharts

http://www.highcharts.com/

**Comment by moklick** [comment]
Hi @stpoa,

1. I don't know where they are. 
2. I don't know if it's the most advanced JavaScript charting library on earth.

If you want to add something you can do a pull request.

Best,

Moritz
