### ISSUE TITLE
Displaying times

### ISSUE THREAD

**Issue by jayay** [moklick/frontend-stuff#3]
[moment.js](http://momentjs.com/) is nice if you want your time outputs to be more readable. I think it should be part of the list.

**Comment by johnstew** [comment]
Keeping this whole time thing going. I usually write my own for this kind of stuff but I have used [timeago](http://timeago.yarp.com/) which is a jQuery Plugin for timestamps. These two could be a good addition together.

**Comment by moklick** [comment]
moment.js is awesome. I will add it to the list.
