### ISSUE TITLE
Can i add Java Script frame works in to it?

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [moklick/frontend-stuff#7]
Adding JS frameworks will also help the people, i guess.

**Comment by moklick** [comment]
Sure but I think that we do not need to list the big players like Angular, Backbone, Ember etc. Maybe stuff like Riot, Mithril and Ampersand?! It's more a list of things I don't want to forget. That's the reason why there is no jquery on the list ;)

**Comment by rajeshwarpatlolla** [comment]
Now it got more than 800 starts, so now you are not just helping yourself to remember these, but also so many people. Many folks are using your stuff. So i think adding what ever related to front end / UI will help people.

**Comment by moklick** [comment]
It'S a good point but If you google something like "Javascript MVC" you will immediately find "Backbone", "Angular" etc. So which frameworks would you add to the list?

**Comment by rajeshwarpatlolla** [comment]
I want to add all the frameworks like Angular JS, Backbone JS, Ember JS, Ext JS, and also platforms like Node.js and its framework Express JS, Happy JS.

**Comment by dbalas** [comment]
There is no sense to add frameworks in this repository, maybe you could make reference to http://todomvc.com/

**Comment by rajeshwarpatlolla** [comment]
Thanks
